### ISSUE TITLE
ERROR when i press add card button

### ISSUE THREAD

**Issue by bsudhanva** [glutanimate/image-occlusion-enhanced#162]
#### Problem description
i get an error when i press add card button

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [x ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Error
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-28 12:31:48

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 464, in handler
  File "C:\Users\abcd\AppData\Roaming\Anki2\addons21\1374772155\add.py", line 278, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(choice, close, val))
  File "C:\Users\abcd\AppData\Roaming\Anki2\addons21\1374772155\add.py", line 293, in _onAddNotesButton
    r = gen.generateNotes()
  File "C:\Users\abcd\AppData\Roaming\Anki2\addons21\1374772155\ngen.py", line 80, in generateNotes
    (svg_node, layer_node) = self._getMnodesAndSetIds()
  File "C:\Users\abcd\AppData\Roaming\Anki2\addons21\1374772155\ngen.py", line 190, in _getMnodesAndSetIds
    mask_doc = minidom.parseString(self.new_svg.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-07-28 12:31:48

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 464, in handler
  File "C:\Users\abcd\AppData\Roaming\Anki2\addons21\1374772155\add.py", line 278, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(choice, close, val))
  File "C:\Users\abcd\AppData\Roaming\Anki2\addons21\1374772155\add.py", line 293, in _onAddNotesButton
    r = gen.generateNotes()
  File "C:\Users\abcd\AppData\Roaming\Anki2\addons21\1374772155\ngen.py", line 80, in generateNotes
    (svg_node, layer_node) = self._getMnodesAndSetIds()
  File "C:\Users\abcd\AppData\Roaming\Anki2\addons21\1374772155\ngen.py", line 190, in _getMnodesAndSetIds
    mask_doc = minidom.parseString(self.new_svg.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'

```

**Comment by bsudhanva** [comment]
i found the solution there is a typo in the ngen.py file instead of utf-8 utf8 is present, after making this change im got getting any error
