### ISSUE TITLE
Incompatible with "Hoochiepapa randomize new queue" add-on

### ISSUE THREAD

**Issue by DragsTheKnee** [glutanimate/image-occlusion-enhanced#166]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [x ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
    Platform: Mac 10.15.6
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-08-08 18:45:07
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS add-on ['0amboss_addon', 2020-07-20T09:55, 'None', '']
    BetterTags ['bettertags', 2020-04-28T11:40, 'None', '']
    Custom background update ['custom_background_update', 0, 'None', mod]
    HoochiePapa Randomize New Queue ['1173108619', 2020-04-24T23:17, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T22:21, 'None', '']
    Review Heatmap ['review_heatmap', 2018-10-28T18:06, 'None', '']
    Special Fields ['1102281552', 2020-07-26T17:22, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1102281552 1173108619 1374772155
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Custom Background Image and Gear Icon ['1210908941', 2020-04-17T17:38, 'None', mod]

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-08 18:45:07
Add-ons possibly involved: ⁨Review Heatmap⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 544, in _onBridgeCmd
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-28>", line 2, in _linkHandler
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/Max/Library/Application Support/Anki2/addons21/review_heatmap/links.py", line 74, in heatmapLinkHandler
    return None if not _old else _old(self, url)
  File "aqt/overview.py", line 67, in _linkHandler
  File "aqt/main.py", line 646, in moveToState
  File "aqt/main.py", line 668, in _reviewState
  File "aqt/reviewer.py", line 65, in show
  File "aqt/reviewer.py", line 110, in nextCard
  File "anki/schedv2.py", line 62, in getCard
  File "anki/sched.py", line 172, in _getCard
  File "anki/schedv2.py", line 328, in _getNewCard
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-6>", line 2, in _fillNew
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
TypeError: fillNew() got multiple values for argument '_old'
```

**Comment by galantra** [comment]
I use both together and don't get this error in any situation.
