### ISSUE TITLE
Image-occlusion enhanced

### ISSUE THREAD

**Issue by BKipz** [Glutanimate/image-occlusion-enhanced#18]
Hello, I am wondering if you can help...I am trying to use image occlusion. Whenever, I click on add 'non-overlapping' or 'add over-lapping' tabs...or after I have done so and I click close, the following bug report window opens up (the reports have been getting longer the more times I keep using image occlusion): 
If that doesn't fix the problem, please copy the following
into a bug report:

Traceback (most recent call last):
File "aqt\webview.py", line 157, in _loadFinished
File "aqt\editor.py", line 507, in _loadFinished
File "aqt\editor.py", line 539, in loadNote
File "anki\notes.py", line 89, in items
IndexError: list index out of range

An error occurred. It may have been caused by a harmless bug, 
or your deck may have a problem.
To confirm it's not a problem with your deck, please run Tools > Check Database.

If that doesn't fix the problem, please copy the following
into a bug report:

Traceback (most recent call last):
File "aqt\webview.py", line 157, in _loadFinished
File "aqt\editor.py", line 507, in _loadFinished
File "aqt\editor.py", line 539, in loadNote
File "anki\notes.py", line 89, in items
IndexError: list index out of range
Traceback (most recent call last):
File "aqt\webview.py", line 157, in _loadFinished
File "aqt\reviewer.py", line 182, in <lambda>
File "aqt\reviewer.py", line 207, in _showQuestion
File "anki\cards.py", line 120, in q
File "anki\cards.py", line 137, in _getQA
File "anki\collection.py", line 501, in _renderQA
IndexError: list index out of range

**Comment by BKipz** [comment]
I am not sure where to report the bug, I'd appreciate any help. I have already checked Database and ran optimized my decks...but this has not solved the problem :(

**Comment by Glutanimate** [comment]
Please check this wiki entry out: https://github.com/Glutanimate/image-occlusion-enhanced/wiki/Troubleshooting#an-error-message-appears-whenever-i-try-to-review-image-occlusion-cards-or-look-at-them-in-the-browser

**Comment by Glutanimate** [comment]
I'll close this issue for now as it looks like it was resolved.
