### ISSUE TITLE
Error when trying to add a card

### ISSUE THREAD

**Issue by honeyybat** [glutanimate/image-occlusion-enhanced#199]
#### Problem description
I download Anki and the add on the weekend, so I should have the latest updated versions. When I go to add an image by clicking the image icon an error message appears. Seen below. 
I would love to be able to use this add on but I don't know how to get past this error. I have tried many different ways from other how-to videos but I can't seen to get it to work. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*
    
    Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2021-03-22 09:00:52
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T10:21, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

#### Error message (if any)

"An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-22 09:00:52

Caught exception:
Traceback (most recent call last):
  File "anki\config.py", line 37, in get_immutable
  File "anki\_backend\generated.py", line 662, in get_config_json
  File "anki\_backend\__init__.py", line 106, in _run_command
anki.errors.NotFoundError"

**Comment by amicoe** [comment]
Any recommendations as to what to do here? I am receiving the same error even after completing the diagnostic steps outlined above. I would love to use this add-on!
