### ISSUE TITLE
Get an error message ... 

### ISSUE THREAD

**Issue by SvenAERTS228** [glutanimate/image-occlusion-enhanced#206]
It's reported in the forum a couple of times too e.g. 
https://forums.ankiweb.net/t/image-occlusion-enhanced-for-anki-21-alpha-error/4922/5
This is what it looks on my screen after I click the button "Hide one, Guess one".
![Screen Shot 2021-05-12 at 04 10 14](https://user-images.githubusercontent.com/55750172/117909314-50043600-b2da-11eb-92f7-bdc6268100b8.png)
Thy
PS my Error log:
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.30 (06a69c25) Python 3.8.1 Qt 5.9.7 PyQt 5.13.2
Platform: Mac 10.11.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-05-12 03:08:11
Add-ons possibly involved: ⁨Image Occlusion Enhanced for Anki 21 alpha⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 493, in handler
  File "/Users/skypeSvenAERTS/Library/Application Support/Anki2/addons21/1374772155/add.py", line 278, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(choice, close, val))
  File "/Users/skypeSvenAERTS/Library/Application Support/Anki2/addons21/1374772155/add.py", line 293, in _onAddNotesButton
    r = gen.generateNotes()
  File "/Users/skypeSvenAERTS/Library/Application Support/Anki2/addons21/1374772155/ngen.py", line 80, in generateNotes
    (svg_node, layer_node) = self._getMnodesAndSetIds()
  File "/Users/skypeSvenAERTS/Library/Application Support/Anki2/addons21/1374772155/ngen.py", line 190, in _getMnodesAndSetIds
    mask_doc = minidom.parseString(self.new_svg.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by amicoe** [comment]
I also get this same error. When I add a "label" layer onto my image along with a "mask" layer, I am unable to add the card to my deck and receive the error code as seen,  but when I simply use the "mask" layer the card is added without issue. 

note: this occurs with both the add-on 'image occlusion' as well as Image Occlusion Enhanced for Anki 21 alpha⁩. Very frustrating! I've gleaned these blogs for everything and have tried it all. No success yet. I even deleted my updated anki and downloaded the older version in hopes of avoiding "new bugs" without avail! Please HELP!

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-13 10:27:27
Add-ons possibly involved: ⁨Image occlusion⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 515, in handler
  File "/Users/elizabethamico/Library/Application Support/Anki2/addons21/1108947803/add.py", line 278, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(choice, close, val))
  File "/Users/elizabethamico/Library/Application Support/Anki2/addons21/1108947803/add.py", line 293, in _onAddNotesButton
    r = gen.generateNotes()
  File "/Users/elizabethamico/Library/Application Support/Anki2/addons21/1108947803/ngen.py", line 80, in generateNotes
    (svg_node, layer_node) = self._getMnodesAndSetIds()
  File "/Users/elizabethamico/Library/Application Support/Anki2/addons21/1108947803/ngen.py", line 190, in _getMnodesAndSetIds
    mask_doc = minidom.parseString(self.new_svg.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'
