### ISSUE TITLE
Doesn't work with Version ⁨2.1.46 (94913ec2)⁩

### ISSUE THREAD

**Issue by livenlife1219** [glutanimate/image-occlusion-enhanced#216]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?* 

Prompted me to disable the add on and once I did I was able to make my cards

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by med-or-bust** [comment]
I got this error too - here's the error message:

```
Debug info:
Anki 2.1.41 (312fa278) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-08-19 23:12:09
Add-ons possibly involved: ⁨Image Occlusion Enhanced for Anki 21 alpha⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 526, in handler
  File "/Users/vrindadeshpande/Library/Application Support/Anki2/addons21/1374772155/add.py", line 278, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(choice, close, val))
  File "/Users/vrindadeshpande/Library/Application Support/Anki2/addons21/1374772155/add.py", line 293, in _onAddNotesButton
    r = gen.generateNotes()
  File "/Users/vrindadeshpande/Library/Application Support/Anki2/addons21/1374772155/ngen.py", line 80, in generateNotes
    (svg_node, layer_node) = self._getMnodesAndSetIds()
  File "/Users/vrindadeshpande/Library/Application Support/Anki2/addons21/1374772155/ngen.py", line 190, in _getMnodesAndSetIds
    mask_doc = minidom.parseString(self.new_svg.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'

```
