### ISSUE TITLE
Image Occlusion not working after use of pencil tool

### ISSUE THREAD

**Issue by sijin-jade** [glutanimate/image-occlusion-enhanced#231]
#### Problem description

该插件中的铅笔工具失效，即：在用铅笔做好标记后无法添加到Anki中成为卡片！

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```    
    Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-01-28 19:37:47
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T10:21, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AwesomeTTS Google Cloud Text-to-Speech  Microsoft Azure TTS unofficial ['814349176', 2021-06-17T05:08, 'None', '']
    Dict2Anki ['1284759083', 2021-03-16T10:22, 'None', mod]


```

#### Error message (if any)
<img width="960" alt="我快哭了，终于让我找到了" src="https://user-images.githubusercontent.com/98556911/151541291-1c9639ea-5324-44bf-a45d-0887c2e479b3.png">

*If you've received an error message, please copy and paste it between the backticks below:*

```python

错误
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。
调试信息：
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-01-27 16:54:40

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 526, in handler
  File "C:\Users\s1786\AppData\Roaming\Anki2\addons21\1374772155\add.py", line 278, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(choice, close, val))
  File "C:\Users\s1786\AppData\Roaming\Anki2\addons21\1374772155\add.py", line 293, in _onAddNotesButton
    r = gen.generateNotes()
  File "C:\Users\s1786\AppData\Roaming\Anki2\addons21\1374772155\ngen.py", line 80, in generateNotes
    (svg_node, layer_node) = self._getMnodesAndSetIds()
  File "C:\Users\s1786\AppData\Roaming\Anki2\addons21\1374772155\ngen.py", line 190, in _getMnodesAndSetIds
    mask_doc = minidom.parseString(self.new_svg.encode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'encode'

```

**Comment by ghost** [comment]
Any update on this @glutanimate? I use Linux Mint 21 with the latest Anki Qt 6 and I have this problem as well.

```
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-17 10:59:51
Add-ons possibly involved: ⁨Image Occlusion Enhanced⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "/home/tux/.local/share/Anki2/addons21/1374772155/add.py", line 324, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(
  File "/home/tux/.local/share/Anki2/addons21/1374772155/add.py", line 343, in _onAddNotesButton
    r = gen.generateNotes()
  File "/home/tux/.local/share/Anki2/addons21/1374772155/ngen.py", line 99, in generateNotes
    (svg_node, layer_node) = self._getMnodesAndSetIds()
  File "/home/tux/.local/share/Anki2/addons21/1374772155/ngen.py", line 226, in _getMnodesAndSetIds
    mask_doc = minidom.parseString(self.new_svg.encode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'encode'

```

**Comment by glutanimate** [comment]
@Hell01World thanks for the heads-up! Can reproduce the issue here and will look into it. Closing this report in favor of #220
