### ISSUE TITLE
Addon Broken

### ISSUE THREAD

**Issue by l-ucky** [glutanimate/image-occlusion-enhanced#238]
#### Problem description

I'm sorry my title sucks, I don't know how to make it descriptive here. Fresh anki-git download from the AUR, and then tried launching Anki with add-ons enabled. When starting Anki I get this error. I downloaded all of my addons at once from the Anking guy's website. After downloading and copy/pasting the addon contents into my own addon folder, I updated the addons with the Anki gui menu and then restarted it. I still expereince the error. The error goes away only if I disable the add on.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.50 (44342660) Python 3.10.2 Qt 5.15.2 PyQt 5.15.6
    Platform: Linux
    Flags: frz=False ao=True sv=2
    Add-ons, last update check: 2022-03-21 10:18:32
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['popup_dictionary', 0, 'None', mod]
    '' ['put_ALL_due_learning_cards_first', 0, 'None', '']
    Add Hyperlink ['318752047', 2022-02-08T19:21, 'None', '']
    Additional Card Fields Fork for 21 ['744725736', 2022-02-21T18:22, 'None', mod]
    Anki Simulator ['817108664', 2021-08-07T16:24, 'None', '']
    Anki Zoom ['538879081', 2020-04-03T21:20, 'v1.1.3', '']
    Batch Editing ['291119185', 2019-09-19T14:04, 'None', '']
    BetterSearch ['1052724801', 2022-01-25T18:25, 'None', mod]
    Browser Resizer ['1435775540', 2021-08-01T18:11, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2022-01-25T18:11, 'None', mod]
    Clickable Tags v20 ['1739176371', 2022-01-30T18:58, 'None', '']
    Collapsible Fields ['1896168623', 2021-08-28T18:45, 'None', '']
    Convert Subdecks to Tag Hierarchy ['1172858842', 2020-02-23T18:03, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2022-02-24T19:21, 'None', mod]
    Customize Keyboard Shortcuts ['24411424', 2022-03-19T01:46, 'None', mod]
    Edit Field During Review Cloze ['385888438', 2022-02-22T01:35, '6.11', mod]
    Extended Card Stats During Review ['1008566916', 2017-08-29T15:59, 'None', '']
    Extended Tag AddEdit Dialog ['1135507717', 2022-03-13T07:41, 'None', mod]
    Fastbar- with nightmode support ['46611790', 2022-02-04T17:02, 'None', '']
    Free Weekend - or Any Other Day ['742185195', 2020-04-10T08:57, 'None', mod]
    High Yield Tags ['1918380616', 2021-08-06T21:48, 'None', mod]
    Highlight Search Results in the Browser ['225180905', 2021-03-10T13:06, 'None', '']
    Hint Hotkeys ['1844908621', 2019-02-26T14:58, 'None', '']
    Image Editor ['307397307', 2021-12-19T07:58, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T23:21, 'None', '']
    Image Style Editor ['1593969147', 2021-12-17T03:01, 'None', mod]
    ImageResizer ['1214357311', 2022-03-19T22:11, 'None', '']
    Learning Step and Review Interval Retention ['1949865265', 2022-03-14T17:58, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2021-01-27T05:09, 'None', mod]
    More Overview Stats 21 ['738807903', 2021-07-30T16:13, 'None', mod]
    Quick Colour Changing ['2491935955', 2019-03-02T22:26, 'None', mod]
    Rebuild All  Empty All for Anki 21 ['1810938259', 2018-07-20T01:40, 'None', '']
    Resize images in editor ['1103084694', 2021-07-19T03:35, 'None', mod]
    Special Fields ['1102281552', 2022-02-23T13:27, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail/good ['1046608507', 2019-06-02T06:11, 'None', '']
    Symbols As You Type ['2040501954', 2021-03-21T23:17, 'None', '']
    Symbols ['1461102936', 2019-04-23T10:37, 'None', mod]
    Web Browser - Search terms Import texts and images automatically ['864545277', 2022-01-17T17:33, 'None', mod]
    add-on dialog searchfilter bar ['561945101', 2021-12-05T16:28, 'None', '']
    when is next learning card due today due ['563204849', 2021-12-06T11:06, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1008566916 1046608507 1052724801 1102281552 1103084694 1135507717 1172858842 1210908941 1214357311 1374772155 1435775540 1461102936 1556734708 1593969147 1739176371 1810938259 1844908621 1896168623 1918380616 1949865265 2040501954 225180905 24411424 2491935955 291119185 307397307 318752047 385888438 46611790 538879081 561945101 563204849 738807903 742185195 744725736 817108664 831846358 864545277
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2022-01-30T19:07, 'None', '']
    Load Balanced Scheduler ['208879074', 2019-07-23T23:37, 'None', '']
    Mini Format Pack ['295889520', 2019-03-01T23:13, 'None', '']
    Picmonic Anki Add-On ['40737180', 2021-09-29T15:58, 'None', '']
    Puppy Reinforcement ['puppy_reinforcement', 2020-02-05T03:16, 'None', '']
    Reset Ease ['947935257', 2020-12-27T10:59, 'None', '']
    Stats Plus ['1009670238', 2021-03-04T08:23, 'None', '']
    Straight Reward ['957961234', 2021-01-11T08:37, 'None', '']
    Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-19T15:52, 'None', mod]
    Wrapper meta-addon ['396502676', 2021-12-28T14:27, 'None', '']

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.50 (44342660) Python 3.10.2 Qt 5.15.2 PyQt 5.15.6
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-03-21 10:18:32
Add-ons possibly involved: ⁨Image Occlusion Enhanced for Anki 21 alpha⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/progress.py", line 115, in handler
    func()
  File "/usr/lib/python3.10/site-packages/aqt/main.py", line 186, in on_window_init
    fn()
  File "/usr/lib/python3.10/site-packages/aqt/main.py", line 279, in setupProfile
    self.loadProfile()
  File "/usr/lib/python3.10/site-packages/aqt/main.py", line 462, in loadProfile
    gui_hooks.profile_did_open()
  File "/usr/lib/python3.10/site-packages/aqt/hooks_gen.py", line 3077, in __call__
    anki.hooks.runHook("profileLoaded")
  File "/usr/lib/python3.10/site-packages/anki/hooks.py", line 34, in runHook
    func(*args)
  File "/home/lucky/.local/share/Anki2/addons21/1374772155/main.py", line 201, in onProfileLoaded
    editor._html = editor._html + io_editor_style.replace("%", "%%")
AttributeError: module 'aqt.editor' has no attribute '_html'

```

**Comment by l-ucky** [comment]
I can still see the previous IOs I made.

https://i.imgur.com/SfwBqxf.png

**Comment by NavSrijan** [comment]
Having the same issue. Did you find any workaround?

**Comment by l-ucky** [comment]
Hello. I found a solution, but it isn't related to Anki directly, but the Bazel package. I deleted Anki `sudo pacman -Rscn anki` and then I used `sudo rm -rf ~/.cache/bazel`. Following a fresh download after deleting the bazel downloads and anki I was able to get it working

https://github.com/ankitects/anki/blob/main/docs/development.md [search the page for the term 'bazel' under the 'Free Space' heading.
