### ISSUE TITLE
System theme changes can trigger RunTimeError

### ISSUE THREAD

**Issue by glutanimate** [glutanimate/image-occlusion-enhanced#251]
It looks like theme changes that happen while Anki is running (e.g. as a result of the system theme changing between day/night) can sometimes trigger a `RunTimeWarning` due to `ImgOccWebView` having been garbage-collected at that stage.

Reported by [/u/sunflower_ash over on Reddit](https://old.reddit.com/r/Anki/comments/w2tl6i/image_occlusion_enhanced_bug_constantly_coming_up/):

```
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-17 20:43:23
Add-ons possibly involved: ⁨Image Occlusion Enhanced⁩
Caught exception:
Traceback (most recent call last):
File "aqt.progress", line 118, in handler
File "aqt.theme", line 175, in apply_style_if_system_style_changed
File "aqt.theme", line 186, in apply_style
File "aqt.hooks_gen", line 4149, in __call__
File "aqt.webview", line 718, in on_theme_did_change
File "aqt.webview", line 556, in eval
File "aqt.webview", line 559, in evalWithCallback
File "aqt.webview", line 576, in _queueAction
File "/Users/user/Library/Application Support/Anki2/addons21/1374772155/editor.py", line 107, in _maybeRunActions
self._evalWithCallback(*args)
File "aqt.webview", line 572, in _evalWithCallback
RuntimeError: wrapped C/C++ object of type ImgOccWebView has been deleted
```

Anki debug info:

```
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-17 20:43:23


===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Image Occlusion Enhanced ['1374772155', 2022-04-09T15:15, 'None', '']
Review Heatmap ['review_heatmap', 2020-04-30T21:23, 'None', '']

===IDs of active AnkiWeb add-ons===
1374772155

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```

**Comment by slabzzz** [comment]
Hi:
Does this error break the core functionality of this add-on in any way? I would like to keep my system-based theme switching.

**Comment by glutanimate** [comment]
Hey slabzzz, no it basically just causes an error to pop up sometimes when the theme switches (so typically twice a day at most, and even then, only under some particular circumstances). But this is also fixed in the upcoming IOE update which shouldn't be too far off :)
