### ISSUE TITLE
Error immediately after selecting "Add Image Occlusion" option

### ISSUE THREAD

**Issue by ZoeLCKB** [glutanimate/image-occlusion-enhanced#256]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-10 13:26:44

Caught exception:
Traceback (most recent call last):
  File "anki.config", line 43, in get_immutable
  File "anki._backend.generated", line 1004, in get_config_json
  File "anki._backend", line 146, in _run_command
anki.errors.NotFoundError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 624, in _onBridgeCmd
  File "aqt.editor", line 467, in onBridgeCmd
  File "C:\Users\zkohl\AppData\Roaming\Anki2\addons21\1108947803\main.py", line 101, in <lambda>
    lambda o=editor: onImgOccButton(o),
  File "C:\Users\zkohl\AppData\Roaming\Anki2\addons21\1108947803\main.py", line 61, in onImgOccButton
    io_model = getOrCreateModel()
  File "C:\Users\zkohl\AppData\Roaming\Anki2\addons21\1108947803\config.py", line 121, in getOrCreateModel
    model_version = mw.col.conf['imgocc']['version']
  File "anki.config", line 62, in __getitem__
  File "anki.config", line 45, in get_immutable
KeyError

**Comment by glutanimate** [comment]
Hi there, it looks like you're using an outdated version of the add-on downloaded from an unofficial AnkiWeb listing. Please uninstall it and then try installing the official version from here: https://ankiweb.net/shared/info/1374772155

(and please do let me know if that fixes the issue. Thanks!)

**Comment by ZoeLCKB** [comment]
The updated version now works perfectly -- thank you!

________________________________
From: Aristotelis ***@***.***>
Sent: Saturday, September 17, 2022 12:09:07 PM
To: glutanimate/image-occlusion-enhanced
Cc: Zoe Kohler-Boland; Author
Subject: [EXTERNAL] Re: [glutanimate/image-occlusion-enhanced] Error immediately after selecting "Add Image Occlusion" option (Issue #256)


Hi there, it looks like you're using an outdated version of the add-on downloaded from an unofficial AnkiWeb listing. Please uninstall it and then try installing the official version from here: https://ankiweb.net/shared/info/1374772155<https://urldefense.com/v3/__https://ankiweb.net/shared/info/1374772155__;!!Mi0JBg!PmrF8fzm0TjE2pPwxLpZ9xc0gaJ4Jqj44Q4czfsihTF6mmTfOczkNQyYHe_xUYUXrsgwbJbPXK6QOjyCJb3BB1fJeg$>

(and please do let me know if that fixes the issue. Thanks!)
