### ISSUE TITLE
Issue with Image Occulsion

### ISSUE THREAD

**Issue by rohannpatil** [glutanimate/image-occlusion-enhanced#267]
#### Problem description

Attempted to use Image Occlusion to create a card, repeatedly pops up with an error message.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-24 23:39:04

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "C:\Users\rpati\AppData\Roaming\Anki2\addons21\1374772155\add.py", line 324, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(
  File "C:\Users\rpati\AppData\Roaming\Anki2\addons21\1374772155\add.py", line 343, in _onAddNotesButton
    r = gen.generateNotes()
  File "C:\Users\rpati\AppData\Roaming\Anki2\addons21\1374772155\ngen.py", line 99, in generateNotes
    (svg_node, layer_node) = self._getMnodesAndSetIds()
  File "C:\Users\rpati\AppData\Roaming\Anki2\addons21\1374772155\ngen.py", line 226, in _getMnodesAndSetIds
    mask_doc = minidom.parseString(self.new_svg.encode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'encode'

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by JuliusSchaefer** [comment]
I got this error and I checkt it with everything. Hopefully you can help me

Error: Image Occlusion note type not configured properly. Please make sure you did not manually delete or rename any of the default fields.

**Comment by JuliusSchaefer** [comment]
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Mac 13.0
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-10-31 12:41:39
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AMBOSS add-on ['0amboss_addon', 2022-09-08T14:45, 'None', '']
    Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
