### ISSUE TITLE
image oclussion don't add 

### ISSUE THREAD

**Issue by ASC14** [glutanimate/image-occlusion-enhanced#297]
#### Problem description

First of all, thank you very much for this excellent add, I love it and in my daily life as a student I use it a lot.
The bad thing is that when you are making a lot of flashcards, it generates an error when you try to close the tab or in certain cases when you use other tools such as the pencil.

I hope it can be solved very soon.......

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)
An error has occurred. Please start Anki by holding down the Shift and Down arrow keys, which will temporarily disable the extensions you have installed.
If this error persists only when you have extensions activated, use Tools > Extensions Menu to disable an extension and restart Anki, repeating this process until you discover which specific extension is causing the problem.
When you have discovered the extension that was causing the problem, please report this to [extension support site](https://forums.ankiweb.net/c/add-ons/11).

nformación de depuración: 
Anki 2.1.50 (26d40c3a) Python 3.9.7 Qt 6.2.3 PyQt 6.2.3
Platform: Mac 13.5.2
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-09-20 19:19:46
Complementos posiblemente implicados: ⁨Image Occlusion Enhanced⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 557, in handler
  File "/Users/alejandrososa/Library/Application Support/Anki2/addons21/1374772155/add.py", line 324, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(
  File "/Users/alejandrososa/Library/Application Support/Anki2/addons21/1374772155/add.py", line 358, in _onAddNotesButton
    mw.reset()
  File "aqt.main", line 766, in reset
  File "aqt.main", line 718, in _synthesize_op_did_execute_from_reset
  File "aqt.hooks_gen", line 2951, in __call__
  File "aqt.deckchooser", line 120, in on_operation_did_execute
  File "aqt.deckchooser", line 82, in _update_button_label
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted

```python

```

**Comment by foodornt** [comment]
Similar error
