### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by davidaksa** [glutanimate/image-occlusion-enhanced#311]
#### Problem description

Anki keeps freezing due to image occlusion add-on.  In case of an error: I had to force quit anki and restart it. I wouldn't face any problems for a while but after a few hours, the same thing would happen again.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.4.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.theme", line 237, in apply_style
  File "_aqt.hooks", line 5121, in __call__
  File "aqt.webview", line 786, in on_theme_did_change
  File "aqt.webview", line 616, in eval
  File "aqt.webview", line 619, in evalWithCallback
  File "aqt.webview", line 636, in _queueAction
  File "/Users/aksadavid/Library/Application Support/Anki2/addons21/1374772155/editor.py", line 107, in _maybeRunActions
    self._evalWithCallback(*args)
  File "aqt.webview", line 632, in _evalWithCallback
RuntimeError: wrapped C/C++ object of type ImgOccWebView has been deleted

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Button Colours Good Again ['2494384865', 2022-09-27T15:48, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T12:45, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T07:13, 'None', '']
True Retention ['613684242', 2017-11-20T02:13, 'None', '']

===IDs of active AnkiWeb add-ons===
1374772155 1771074083 2494384865 613684242

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])


```

**Comment by thepeacemonk** [comment]
I'm having the same issue, tried the same thing, and also having the same message: 

```

Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.progress", line 119, in handler
  File "aqt.theme", line 237, in apply_style
  File "_aqt.hooks", line 5121, in __call__
  File "aqt.webview", line 786, in on_theme_did_change
  File "aqt.webview", line 616, in eval
  File "aqt.webview", line 619, in evalWithCallback
  File "aqt.webview", line 636, in _queueAction
  File "/Users/gabrielcarusmartins/Library/Application Support/Anki2/addons21/1374772155/editor.py", line 107, in _maybeRunActions
    self._evalWithCallback(*args)
  File "aqt.webview", line 632, in _evalWithCallback
RuntimeError: wrapped C/C++ object of type ImgOccWebView has been deleted

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-10-09T23:36, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T04:15, 'None', '']
Pokemanki Gold - Raising Pokemon with Anki Customized by Shige ['1677779223', 2024-10-13T12:57, 'None', mod]
Review Heatmap ['1771074083', 2022-06-29T22:43, 'None', '']
The KING of Button Add-ons ['374005964', 2024-09-23T09:14, 'None', mod]

===IDs of active AnkiWeb add-ons===
1374772155 1677779223 1771074083 374005964 759844606

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```
