### ISSUE TITLE
Popup error after creating a card about Image Occlusion Add on

### ISSUE THREAD

**Issue by guesswho1234555** [glutanimate/image-occlusion-enhanced#313]
#### Problem description
I receive an error message (listed below) every time I add a new card using the image occlusion add-on.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "aqt.webview", line 628, in handler
  File "C:\Users\aaron\AppData\Roaming\Anki2\addons21\1374772155\add.py", line 324, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(
  File "C:\Users\aaron\AppData\Roaming\Anki2\addons21\1374772155\add.py", line 358, in _onAddNotesButton
    mw.reset()
  File "aqt.main", line 851, in reset
  File "aqt.main", line 803, in _synthesize_op_did_execute_from_reset
  File "_aqt.hooks", line 3840, in __call__
  File "aqt.deckchooser", line 120, in on_operation_did_execute
  File "aqt.deckchooser", line 82, in _update_button_label
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2023-11-13T11:01, 'None', mod]
AnKing Note Types Easy Customization ['952691989', 2024-06-10T05:23, 'None', mod]
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T10:06, 'None', '']
Fast cards reposition ['544982740', 2021-09-19T08:51, 'None', '']
Filtered Deck From Tag ['2058067048', 2023-02-18T19:42, 'None', '']
Find cards from UWorld test ['444814983', 2024-06-07T09:35, 'None', '']
Full Screen Toggle ['1612375712', 2018-08-24T21:21, 'None', '']
Image Occlusion Enhanced for Anki 21 ['1374772155', 2022-04-09T02:15, 'None', '']
Mini Format Pack ['295889520', 2023-11-02T13:00, 'None', '']
New Cards Counter ['635082046', 2022-04-20T15:37, 'None', '']
No Distractions Full Screen Clean review interface WORKING ['1799768115', 2022-11-20T13:04, 'v4.1.8', mod]
Remove card history ['2089200096', 2023-10-18T22:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
The KING of Study Timers ['907028815', 2022-04-20T13:14, 'None', '']
Weekends and Holidays ['1992008104', 2022-12-19T19:24, 'None', mod]
right hand reviews  hjkl answer shortcuts  Handy Answer Keys configurable ['850294128', 2023-05-24T03:59, 'None', mod]
uworld_qid_to_anki_search ['607963104', 2024-04-13T13:56, 'None', mod]

===IDs of active AnkiWeb add-ons===
1374772155 1612375712 1771074083 1799768115 1992008104 2058067048 2089200096 295889520 444814983 544982740 594329229 607963104 635082046 850294128 907028815 952691989

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiHub ['1322529746', 2024-06-17T04:56, 'None', '']
Puppy Reinforcement ['1722658993', 2023-11-16T06:59, 'None', mod]

#### Error message (if any)
Anki encountered a problem. Please follow the troubleshooting steps.

Add-ons possibly involved: ⁨Image Occlusion Enhanced for Anki 21⁩
*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by guesswho1234555** [comment]
Disabling the anking note editor did not help
