### ISSUE TITLE
The add-on crashes, can't even open the image

### ISSUE THREAD

**Issue by lualparedes** [glutanimate/image-occlusion-enhanced#34]
## Steps
1. Create a new card
2. Choose Image Occlusion Enhanced as the type for the card
3. Click on Add Image Occlusion
4. Browse, select the image (a .png) and hit open

## Expected outcome
The Image Occlusion Enhanced editor opens.

## Actual outcome
Anki reports an error message:
```
An error occurred in an add-on.
Please post on the add-on forum:
https://groups.google.com/forum/#!forum/anki-addons

Traceback (most recent call last):
  File "/home/lual/Anki/addons/image_occlusion_enhanced/main.py", line 361, in <lambda>
    lambda o=self: onImgOccButton(self, "add"),
  File "/home/lual/Anki/addons/image_occlusion_enhanced/main.py", line 355, in onImgOccButton
    mw.ImgOccAdd.selImage(oldimg)
  File "/home/lual/Anki/addons/image_occlusion_enhanced/main.py", line 98, in selImage
    self.callImgOccEdit()
  File "/home/lual/Anki/addons/image_occlusion_enhanced/main.py", line 159, in callImgOccEdit
    mw.ImgOccEdit = ImgOccEdit(mw)
  File "/home/lual/Anki/addons/image_occlusion_enhanced/dialogs.py", line 39, in __init__
    self.setupUi()
  File "/home/lual/Anki/addons/image_occlusion_enhanced/dialogs.py", line 59, in setupUi
    self.svg_edit.setCanFocus(True) # focus necessary for hotkeys
AttributeError: 'AnkiWebView' object has no attribute 'setCanFocus'
```

## Aditional info
- Anki version: 2.0.20
- OS: Linux Mint 17.3 Cinnamon 64-bit

---
Thanks in advance! :blush: :+1:

**Comment by glutanimate** [comment]
Thanks for the detailed report. It looks like you are using a very old version of Anki (≈ about 4 years old). That's not your fault, since the versions shipped by a lot of distros tend to be very outdated, but you'll have to upgrade to Anki 2.0.3x at least for the add-on to work properly. Updated builds and packages of Anki can be found [here](https://apps.ankiweb.net/#linux).

**Comment by lualparedes** [comment]
Thanks so much @glutanimate ! :v:

**Comment by glutanimate** [comment]
Glad I could help, @lualparedes :)!
