### ISSUE TITLE
SVG-Edit loading issues with non-latin locale

### ISSUE THREAD

**Issue by glutanimate** [glutanimate/image-occlusion-enhanced#47]
It seems like there are some issues with loading SVG-Edit on Windows systems with a Chinese locale. The most likely culprit are probably non-latin characters either in Anki's path or the path to the image file.

When a user is affected, Image Occlusion's WebView remains blank instead of loading SVG-Edit.

Clicking on any of the "Add" buttons can then result in error messages like the following:

    Traceback (most recent call last):
      File "C:\Users\������\AppData\Roaming\Anki2\addons\image_occlusion_enhanced\dialogs.py", line 224, in addAO
        mw.ImgOccAdd.onAddNotesButton("ao", close)
      File "C:\Users\������\AppData\Roaming\Anki2\addons\image_occlusion_enhanced\main.py", line 238, in onAddNotesButton
        r = gen.generateNotes()
      File "C:\Users\������\AppData\Roaming\Anki2\addons\image_occlusion_enhanced\ngen.py", line 81, in generateNotes
        ( svg_node, layer_node ) = self._getMnodesAndSetIds()
      File "C:\Users\������\AppData\Roaming\Anki2\addons\image_occlusion_enhanced\ngen.py", line 190, in _getMnodesAndSetIds
        mask_doc = minidom.parseString(self.new_svg.encode('utf-8'))
      File "xml\dom\minidom.py", line 1928, in parseString
      File "xml\dom\expatbuilder.py", line 940, in parseString
      File "xml\dom\expatbuilder.py", line 223, in parseString
    xml.parsers.expat.ExpatError: syntax error: line 1, column 0﻿

Most likely caused by a missing check for a valid SVG file (SVG-Edit is not there, so it can't produce a valid SVG).

**Comment by glutanimate** [comment]
Just managed to perform a series of extensive tests across Windows, macOS, and Linux, and I'm happy to say that this issue seems to be fixed on Anki 2.1. Not sure what prompted this change, probably a modification in how QUrl.fromLocalFile processes unicode strings under PyQt5 / Python 3. 

Marking as solved. Though if anyone manages to find a viable workaround for Anki 2.0, I'd be more than happy to merge it.
