### ISSUE TITLE
Renaming additional user-defined from the field manager causes a KeyError when launching IO

### ISSUE THREAD

**Issue by glutanimate** [glutanimate/image-occlusion-enhanced#48]
[As reported by Anki user Fin](https://anki.tenderapp.com/discussions/add-ons/8295-image-occlusion-enhanced-official-thread#comment_44699513):

```
Traceback (most recent call last): 
  File "/Users/Fin/Library/Application Support/Anki2/addons/image_occlusion_enhanced/main.py", line 361, in <lambda> 
    lambda o=self: onImgOccButton(self, "add"), 
  File "/Users/Fin/Library/Application Support/Anki2/addons/image_occlusion_enhanced/main.py", line 355, in onImgOccButton 
    mw.ImgOccAdd.selImage(oldimg) 
  File "/Users/Fin/Library/Application Support/Anki2/addons/image_occlusion_enhanced/main.py", line 98, in selImage 
    self.callImgOccEdit() 
  File "/Users/Fin/Library/Application Support/Anki2/addons/image_occlusion_enhanced/main.py", line 156, in callImgOccEdit 
    mw.ImgOccEdit.resetWindow() 
  File "/Users/Fin/Library/Application Support/Anki2/addons/image_occlusion_enhanced/dialogs.py", line 257, in resetWindow 
    self.resetAllFields() 
  File "/Users/Fin/Library/Application Support/Anki2/addons/image_occlusion_enhanced/dialogs.py", line 363, in resetAllFields 
    self.resetMainFields() 
  File "/Users/Fin/Library/Application Support/Anki2/addons/image_occlusion_enhanced/dialogs.py", line 359, in resetMainFields 
    self.tedit[fn].setPlainText("") 
KeyError: u'NameS'
```

We currently only call mw.ImgOccEdit.setupFields(flds) once when creating the IO window. This works fine as long as we can guarantee that a user has only edited fields through IO's own options menu. However, since additional user-defined fields may only be edited via Anki's own note type manager we should also account for that possibility.

**Temporary workaround**

If you are affected by the issue above, restarting Anki should put things back in order (as outlined in the [general troubleshooting guide](https://github.com/glutanimate/image-occlusion-enhanced/wiki/Troubleshooting).

**Comment by glutanimate** [comment]
With I/O being reinstatiated with every new I/O session now, the original issue title is no longer accurate. The problem is now limited to instances where a user modifies the I/O note type while an I/O session is running.

In order to address this and other similar issues ideally we would have to add a hook to the `reset` event, but this could end up being pretty complex given how interwoven ImgOccAdd and ImgOccEdit currently are.

Lowering priority as this is now even more of a corner case. Also leaving a note to address this in the alpha description.
